version: '3.9'
services:
  postgres:
    image: postgres:12.10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      # copy the sql script to create database and users
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      # copy the sql script to create tables
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
